### ISSUE TITLE
Logo Proposal for space-x-explorer

### ISSUE THREAD

**Issue by candyskull920** [AndreVarandas/space-x-explorer#20]
Hello @AndreVarandas 
I am an open source enthusiast and I am looking to expand my work portfolio.
I would like to collaborate with your project for free, I can provide a logo for your application

Good day
Skull C.

**Comment by AndreVarandas** [comment]
Hello @candyskull920 thank you for your interest. Please, thank you :) 
Would you also like to work on our splash screen? Could be the same icon. 
Feel free to submit any pull requests.

Have a good day,
Varandas

**Comment by candyskull920** [comment]
Hi @AndreVarandas 
Good day.
I would like to know exactly what it is about
your project, and if you want something specific or something in mind for the logo.

**Comment by AndreVarandas** [comment]
Hi @candyskull920 , good day.

I have shamelessly downloaded a free from google that you can see [here.](https://github.com/AndreVarandas/space-x-explorer/blob/master/resources/icon.png) 

As the application provides data about Tesla space x project, I thought that a rocket would be nice. Or maybe a simple moon/asteroid, I think it would fit perfectly. I'm open to suggestions :)

**Comment by AndreVarandas** [comment]
Hello @candyskull920 the project name is the same as the repository `Space X Explorer`.

Thank you for your interest, have a good day,
André Varandas

**Comment by candyskull920** [comment]
Hi @AndreVarandas 
This is my proposal, I plan to add the name of the project and we would leave as an icon for the app the rocket and the complete composition for the readme.
![logo-1](https://user-images.githubusercontent.com/43797200/46703696-c8239000-cbf5-11e8-8499-7048bacf6cb4.jpg)
![logo-2](https://user-images.githubusercontent.com/43797200/46703711-d4a7e880-cbf5-11e8-83da-83e9f6b257e8.jpg)

**Comment by AndreVarandas** [comment]
Hi @candyskull920 looks awesome! 
Please, make any changes to the readme/assets folder that you would like, replacing the old splash and icon. 

Have a good day,
Varandas
👍

**Comment by AndreVarandas** [comment]
Hello @candyskull920 can I make one last request? 
Could the logo-2.jpg be with transparent background so we can generate a perfect app icon?

Thank you for your time, good day,
Varandas

**Comment by candyskull920** [comment]
Hi @AndreVarandas 
Of course no problem soon I will pass a drive with all the variations and formats of the logo.

Skull C.

**Comment by mcmonkey4eva** [comment]
@AndreVarandas the logo was pulled into the repo and `README.md` file as
```
![logo-2.jpg](https://github.com/candyskull920/space-x-explorer/blob/master/resources/logo-2.jpg?raw=true)
```
I would advise you change that to
```
![logo-2.jpg](/resources/logo-2.jpg?raw=true)
```
^ Using a relative path. This prevents the image being linked to @candyskull920 's fork and retains it within the local repo automatically.

**Comment by candyskull920** [comment]
Hellow @mcmonkey4eva 
ok thanks for the advice I'll take it into account.

Good day
Skull C.

**Comment by AndreVarandas** [comment]
@mcmonkey4eva Thank you for pointing it out. 👍 
`README.md` updated to use a relative path in image source.
